### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by AlifPandu** [CodeDoctorDE/ItemMods#1]
[01:20:45 ERROR]: Could not load 'plugins\ItemMods.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `com.github.codedoctorde.itemmods.Main'
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:70) ~[server.jar:git-Paper-345]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[server.jar:git-Paper-345]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[server.jar:git-Paper-345]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[server.jar:git-Paper-345]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:360) ~[server.jar:git-Paper-345]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[server.jar:git-Paper-345]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:907) ~[server.jar:git-Paper-345]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.ClassNotFoundException: com.github.codedoctorde.itemmods.Main
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_144]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[server.jar:git-Paper-345]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[server.jar:git-Paper-345]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_144]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_144]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[server.jar:git-Paper-345]

**Comment by CodeDoctorDE** [comment]
oh sry, forget to set the new main class :D next bug fix update comes

**Comment by CodeDoctorDE** [comment]
should be fixed! thanks for your report :D
