### ISSUE TITLE
NullPointerException on giveItemStack

### ISSUE THREAD

**Issue by 3Lord3** [CodeDoctorDE/ItemMods#3]
`[19:12:19 ERROR]: Could not pass event InventoryClickEvent to ItemMods v1.3.2
java.lang.NullPointerException: null
at com.github.codedoctorde.itemmods.config.ItemConfig.giveItemStack(ItemConfig.java:159) ~[?:?]
at com.github.codedoctorde.itemmods.gui.ItemGui$2$9.onEvent(ItemGui.java:211) ~[?:?]
at com.gitlab.codedoctorde.api.ui.GuiItem.raiseEvent(GuiItem.java:56) ~[?:?]
at com.gitlab.codedoctorde.api.ui.Gui.onInventoryClick(Gui.java:159) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor299.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[minecraft_server.jar:git-Paper-134]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[minecraft_server.jar:git-Paper-134]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[minecraft_server.jar:git-Paper-134]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[minecraft_server.jar:git-Paper-134]
at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:2423) ~[minecraft_server.jar:git-Paper-134]
at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[minecraft_server.jar:git-Paper-134]
at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[minecraft_server.jar:git-Paper-134]
at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[minecraft_server.jar:git-Paper-134]
at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[minecraft_server.jar:git-Paper-134]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[minecraft_server.jar:git-Paper-134]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[minecraft_server.jar:git-Paper-134]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[minecraft_server.jar:git-Paper-134]
at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1137) ~[minecraft_server.jar:git-Paper-134]
at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1130) ~[minecraft_server.jar:git-Paper-134]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[minecraft_server.jar:git-Paper-134]
at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1260) ~[minecraft_server.jar:git-Paper-134]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[minecraft_server.jar:git-Paper-134]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[minecraft_server.jar:git-Paper-134]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]`

![image](https://user-images.githubusercontent.com/62335161/89735767-de126e00-da75-11ea-944d-912a407fdff0.png)
![image](https://user-images.githubusercontent.com/62335161/89735774-e5397c00-da75-11ea-8806-6fa34b889ee6.png)

**Comment by CodeDoctorDE** [comment]
you need an itemstack before giving the item

**Comment by CodeDoctorDE** [comment]
but i can give it an error message if you want

**Comment by 3Lord3** [comment]
Okay, add a message
